version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orthogonality
    ports:
      - "5435:5432"
    volumes:
      - db_volume:/var/lib/postgresql/ortho_data

volumes:
  db_volume: